### ISSUE TITLE
fail to recognize serial port

### ISSUE THREAD

**Issue by hamortar** [vlasovskikh/intellij-micropython#90] opened 2019-05-07 18:03 UTC
I want to upload a Micropython file to an attached ESP8266, but Pycharm does not recognize the serial port in my MacOS.
I am pretty sure both the port and the driver are ok, since I can use uPyCraft with no incident.
At the Preferences/Language & Frameworks/Micropython screen I have specified the device type and the serial port path, but still Pycharm does not connect

**Comment by ivkond** [comment] 2019-08-23 09:35
Please, provide more detailed steps:
- when PyCharm does not recognize the port?
- does plugin Serial Monitor able to connect to device?
- do you change connection baud rate?

**Comment by vlasovskikh** [comment] 2020-06-05 20:54
@hamortar Closing this issue as obsolete. Feel free to open another one if the problem is still relevant to you.

**Closed by vlasovskikh** 2020-06-05 20:54 UTC
Labels: ESP8266, bug, flash to device
