### ISSUE TITLE
Type hints for Pin class are incomplete

### ISSUE THREAD

**Issue by Streyder** [vlasovskikh/intellij-micropython#60] opened 2018-06-21 17:20 UTC
Hey,

the Pin class is sadly lacking some type hints. For example Pin.board.X, Pin.high() and Pin.low() are missing.

Cheers
Kevin

**Comment by vlasovskikh** [comment] 2018-07-24 23:54
@Streyder Thanks for reporting it. A pull request with missing type hints is welcome.

**Comment by Streyder** [comment] 2018-08-09 15:14
I implemented the changes on my end. Sadly I am not allowed to create a new branch to create a pull request. Actually I don't know how I would make a proper pull request. Maybe you can help out.

**Comment by vlasovskikh** [comment] 2018-08-09 17:06
@Streyder We use the standard GitHub workflow for pull requests to this repository, I'm sure there are good tutorials about pull requests on GitHub. The basic idea is that you close this repository to your account, so it becomes github.com/Streyder/intellij-micropython, then you create your new branch there and then GitHub will show you the message about creating a pull request to the original repository on the page of your clone.

**Comment by Streyder** [comment] 2018-08-10 08:01
Created pullrequest [63](https://github.com/vlasovskikh/intellij-micropython/pull/63) for this issue

**Comment by vlasovskikh** [comment] 2020-06-06 10:33
Closing it as a duplicate of #16.

**Closed by vlasovskikh** 2020-06-06 10:33 UTC
Labels: bug, help wanted, type hints
