### ISSUE TITLE
Possible analog_period_microseconds() issue.

### ISSUE THREAD

**Issue by md00bm** [vlasovskikh/intellij-micropython#66] opened 2018-10-27 00:41 UTC
Hi,
Can't seem to set analog_period_microseconds() with value less than 1000. The error message says: "ValueError invalid period". Can anyone confirm this?

```python
pin0.set_analog_period_microseconds(500) # Cannot set below 1000?
```

-----------------------------------------------------------------------------------------------------------
Note:
I tested the code under Mu 1.0.1 and the period can be set to the minimum value of 256:
```python
from microbit import *

pin0.set_analog_period_microseconds(256) # Cannot set below 1000?
oldValue = 0
potValue = 0
while True:
    potValue = pin1.read_analog()
    if potValue > oldValue+3 or potValue < oldValue-3:
        pin0.write_analog(potValue)
        oldValue = potValue
```

**Comment by junhuanchen** [comment] 2018-10-28 06:41
Hi

This question should be asked by micropyhton at microbit.

**Comment by md00bm** [comment] 2018-10-28 11:52
Hi,
The Micro:bit team does not find anything wrong with the code under Mu, only in Pycharm with this MicroPython plugin.

The reply from the Micro:bit team:
Thanks for contacting micro:bit. I can't seem to recreate the error using Mu with micropython v1.0

**Comment by carlosperate** [comment] 2018-10-30 14:19
The uFlash dependency is likely at version 1.1, which would be an old version of MicroPython. https://github.com/vlasovskikh/intellij-micropython/blob/818f868da975f5c51b168db183fa171f9e31fe42/src/main/kotlin/com/jetbrains/micropython/devices/MicroBitDeviceProvider.kt#L46

If the issue cannot be replicated in Mu v1.0 (containing the latest micro:bit MicroPython v1.0.0) then issue was likely a problem already fixed in micro:bit MicroPython.

**Comment by md00bm** [comment] 2018-10-30 15:31
Hi Carlos,
I have searched for uFlash and update the version. But PyCharm seems to install the old version (1.0.8) in the project:

![2018-10-30_23-26-50](https://user-images.githubusercontent.com/38929885/47729710-a325b880-dc9b-11e8-9d31-f69f09284e02.jpg)

How can we solve this problem? Thanks for the input.

**Comment by vlasovskikh** [comment] 2018-10-31 16:16
If the issue is only in the version of uflash used by the plugin, then a pull request is welcome. @md00bm has mentioned the place in the code where the change is required.

**Comment by md00bm** [comment] 2018-11-02 11:30
Dear Andrey,
I have tried to contribute by creating the pull request for newer version of uflash as per suggestion. Totally not sure what I am doing, just edited the line metioned by @carlosperate:
from:
return manager.parseRequirements("""|uflash>=1.0.8,<1.1
                                        |pyserial>=3.3,<4.0""".trimMargin())
to:
return manager.parseRequirements("""|uflash>=1.2.3,<=1.2.3
                                        |pyserial>=3.3,<4.0""".trimMargin())

If there is any mistake please just correct it, anyone. Thanks.

Right now whenever I click on the "install requirements":
![2018-11-02_19-15-47](https://user-images.githubusercontent.com/38929885/47912614-44974f00-ded4-11e8-8df5-bac8a1a73592.jpg)

it will automatically install uflash 1.0.8 section:
![2018-11-02_19-17-06](https://user-images.githubusercontent.com/38929885/47912624-4cef8a00-ded4-11e8-9a79-4af9b5d32e5f.jpg)

Is there anything I can do to change that to uFlash 1.2.3?

Another error I encounter when creating micro:bit projects is "No devices detected.", but micro:bit is shown in File Explorer:
![2018-11-02_19-11-45](https://user-images.githubusercontent.com/38929885/47912775-b7a0c580-ded4-11e8-9487-d70bfb414c3a.jpg)

But the error does not affect file flashing though.

As for the original issue of this thread, analog_period_microseconds(), I think it is a separate issue from uFlash versioning. But can only know after the plugin installs the uFlash section showing 1.2.3, and test the code again.

**Comment by vlasovskikh** [comment] 2018-12-06 15:39
@md00bm Sorry for my late response. Please try to update `uflash` for your virtualenv manally to check if the most recent version has fixed the problem indeed.

You can do it in PyCharm via the list of packages in "File | Settings | Project | Project Interpreter". Select the line with `uflash` and invoke the "Upgrade" action. Alternatively, you can activate your virtualenv in the system console and run `pip install -U uflash` there. Just make sure you've activated the correct virtualenv via its </path/to/your/virtualenv>/bin/activate script.

Please tell if upgrading to uflash 1.2.3 has helped.

**Comment by vlasovskikh** [comment] 2018-12-06 15:44
@md00bm Regarding the second problem with the device detection process (by the way, I would really prefer to have separate issues for unrelated problems): device detection is based on USB vendor ID / product ID values for a serial controller of your MicroPython device. For Micro:bit we have now only a single pair of vendor ID / product ID, see https://github.com/vlasovskikh/intellij-micropython/blob/master/src/main/kotlin/com/jetbrains/micropython/devices/MicroBitDeviceProvider.kt#L42.

You can determine your vendor ID / product ID by exploring the results of `comports() from `serial.tools.list_ports`. See [this helper script](https://github.com/vlasovskikh/intellij-micropython/blob/master/scripts/findusb.py) for an idea of how to explore your connected USB devices.

**Closed** 2020-06-05 19:05 UTC
Labels: Micro:bit, wait for reply
