### ISSUE TITLE
Flashing of project does not ignore excluded folders

### ISSUE THREAD

**Issue by roamingthings** [vlasovskikh/intellij-micropython#51] opened 2018-03-17 11:33 UTC
Hi,

I've setup the plugin to flash all files of my project excluding the .idea folder as described. However the plugin still uploads the .idea folder to the pyboard.

Any thoughts?

**Comment by RoundBobin** [comment] 2018-03-20 16:42
I'd like to provide a way around if you like.

cd ~/Library/Application\ Support/PyCharmCE2017.3/intellij-micropython/scripts/
edit microupload.py file and add something like this

excluded_files = opts['--exclude']
excluded_files.extend(['.git','.DS_Store'])
...
    for x in list_files(root, excluded_files)]

**Comment by vlasovskikh** [comment] 2018-05-30 16:05
@RoundBobin A simple solution like hard-coded .git/, .DS_Store/ and other folder could work. For an alternative fix idea that takes into account the actual file patterns ignored by IntelliJ see my comments in #46.

**Comment by vlasovskikh** [comment] 2018-05-30 16:12
Closing this issue as a duplicate of #46. Please vote for the new issue using :+1:.

**Closed by vlasovskikh** 2018-05-30 16:12 UTC
Labels: bug, flash to device
