### ISSUE TITLE
REPL, line edit, history, releasing COM port

### ISSUE THREAD

**Issue by otalado** [vlasovskikh/intellij-micropython#48] opened 2018-02-28 08:48 UTC
Not really issue but more of usability issues: 
- I really wish that it would be possible to fix typing errors when in REPL
- I wish to be able to recall lines from history when in REPL
- I often get stuck with COM port not being closed/released. Very annoying. I wish to have an obvious way to see status of COM port and a way to release it (tools button/context menu ?).

Other than that, I find micropython plugin **fantastic tool.** Congratulations!

**Comment by otalado** [comment] 2018-03-01 09:19
Hi, I have to retract my comments above. I found an explanation for my situation in issue #43. It turns out it is happening on W10 platform. I installed PyCharm on Raspberry PI /Raspbian (Debian) 9 - everything works OK!
I hope this will be solved for W10 sooner or later, because I can use the RPI installation, but it is slooow...

**Comment by vlasovskikh** [comment] 2018-03-01 11:53
@otalado Thanks for your comments! Closing this one as a duplicate of #43.

**Closed by vlasovskikh** 2018-03-01 11:53 UTC
