### ISSUE TITLE
ampy.pyboard.PyboardError: failed to access COM5

### ISSUE THREAD

**Issue by caole08** [vlasovskikh/intellij-micropython#99] opened 2020-01-13 03:03 UTC
C:\Users\79966\Anaconda3\python.exe C:\Users\79966\.PyCharm2019.1\config\plugins\intellij-micropython/scripts/microupload.py -C C:/Users/79966/PycharmProjects/untitled2 -v COM5 C:/Users/79966/PycharmProjects/untitled2/main.py
Connecting to COM5
Traceback (most recent call last):
  File "C:\Users\79966\.PyCharm2019.1\config\plugins\intellij-micropython/scripts/microupload.py", line 138, in <module>
    main(sys.argv[1:])
  File "C:\Users\79966\.PyCharm2019.1\config\plugins\intellij-micropython/scripts/microupload.py", line 56, in main
    board = Pyboard(port)
  File "C:\Users\79966\Anaconda3\lib\site-packages\ampy\pyboard.py", line 147, in __init__
    raise PyboardError('failed to access ' + device)
ampy.pyboard.PyboardError: failed to access COM5

**Comment by patfrench** [comment] 2020-03-25 16:17
Hi,
I have a same problem, same error. with anaconda3

![image](https://user-images.githubusercontent.com/44723412/77559089-054c1280-6ebc-11ea-867b-8dcd7273289d.png)

![image](https://user-images.githubusercontent.com/44723412/77559174-20b71d80-6ebc-11ea-8c4b-b621adcc0a7d.png)


FLASH : problem
REPL : ok

thank you

**Comment by vlasovskikh** [comment] 2020-06-05 21:43
Sorry for my late reply. Does the "Detect" button work in the MicroPython settings next to the "Device path" on your screenshot? Does it determine the same COM device path that you specify manually? I suppose that your Windows assigned a different COM number to your device. Sorry I don't have a Windows machine available at this moment, so I cannot reproduce this issue.

**Comment by vlasovskikh** [comment] 2020-06-13 19:53
Closing this issue as obsolete. Please feel free to comment it if the problem persists.

**Closed by vlasovskikh** 2020-06-13 19:53 UTC
Labels: Windows, bug, can't reproduce, flash to device
